import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  overviewSidebar: [
    'overview/learning-path',
    {
      type: 'link',
      label: '从0到1搭建四足机器人',
      href: '/docs/practices/quadruped/cs123/intro',
    },
  ],

  foundationsOverviewSidebar: [
    'foundations/intro',
    {
      type: 'category',
      label: '入门认知',
      collapsed: false,
      items: [
        { type: 'link', label: '具身智能入门', href: '/docs/foundations/embodied-ai-intro/placeholder' },
      ],
    },
    {
      type: 'category',
      label: '大脑：智能决策',
      collapsed: false,
      items: [
        { type: 'link', label: '强化学习决策', href: '/docs/foundations/rl-for-robotics/intro' },
        { type: 'link', label: '视觉-语言-动作大模型(VLA)', href: '/docs/foundations/vla/vla-intro' },
        { type: 'link', label: '世界模型(World Model)', href: '/docs/foundations/world-model/placeholder' },
      ],
    },
    {
      type: 'category',
      label: '小脑：运动控制',
      collapsed: false,
      items: [
        { type: 'link', label: '强化学习控制', href: '/docs/foundations/rl-for-robotics/ppo' },
        { type: 'link', label: '控制器', href: '/docs/foundations/controllers/intro' },
        { type: 'link', label: '运动规划', href: '/docs/foundations/robotics-and-ros2/moveit2_basics' },
      ],
    },
    {
      type: 'category',
      label: '感官：感知系统',
      collapsed: false,
      items: [
        { type: 'link', label: '视觉语言大模型(VLM)', href: '/docs/foundations/vlm/intro' },
        { type: 'link', label: '定位与触觉感知', href: '/docs/foundations/perception/placeholder' },
      ],
    },
    {
      type: 'category',
      label: '工程底座',
      collapsed: false,
      items: [
        { type: 'link', label: '仿真工具', href: '/docs/foundations/simulation/intro' },
        { type: 'link', label: 'ROS2', href: '/docs/foundations/robotics-and-ros2/intro' },
        { type: 'link', label: 'CAN 与 MCU 通信', href: '/docs/foundations/communication/can-mcu' },
        { type: 'link', label: '机械结构', href: '/docs/foundations/hardware/placeholder' },
        { type: 'link', label: '数据工程与模仿学习', href: '/docs/foundations/rl-for-robotics/imitation-learning' },
      ],
    },
  ],

  foundationsEmbodiedAiIntroSidebar: [
    {
      type: 'category',
      label: '具身智能入门',
      link: { type: 'doc', id: 'foundations/embodied-ai-intro/placeholder' },
      collapsible: false,
      items: [{ type: 'autogenerated', dirName: 'foundations/embodied-ai-intro' }],
    },
  ],

  foundationsRoboticsAndRos2Sidebar: [
    {
      type: 'category',
      label: 'ROS2',
      link: { type: 'doc', id: 'foundations/robotics-and-ros2/intro' },
      collapsible: false,
      items: [{ type: 'autogenerated', dirName: 'foundations/robotics-and-ros2' }],
    },
  ],

  foundationsSimulationSidebar: [
    {
      type: 'category',
      label: '仿真工具',
      link: { type: 'doc', id: 'foundations/simulation/intro' },
      collapsible: false,
      items: [{ type: 'autogenerated', dirName: 'foundations/simulation' }],
    },
  ],

  foundationsRlForRoboticsSidebar: [
    {
      type: 'category',
      label: '强化学习与控制',
      link: { type: 'doc', id: 'foundations/rl-for-robotics/intro' },
      collapsible: false,
      items: [{ type: 'autogenerated', dirName: 'foundations/rl-for-robotics' }],
    },
  ],

  foundationsControllersSidebar: [
    {
      type: 'category',
      label: '控制器',
      link: { type: 'doc', id: 'foundations/controllers/intro' },
      collapsible: false,
      items: [
        { type: 'doc', id: 'foundations/controllers/feedback-pid', label: '1. 闭环与 PID' },
        { type: 'doc', id: 'foundations/controllers/pid-engineering', label: '2. PID 工程' },
        { type: 'doc', id: 'foundations/controllers/state-space-lqr', label: '3. LQR' },
        { type: 'doc', id: 'foundations/controllers/trajectory-tracking', label: '4. 轨迹跟踪' },
        { type: 'doc', id: 'foundations/controllers/mpc', label: '5. MPC' },
        { type: 'doc', id: 'foundations/controllers/impedance-force-control', label: '6. 阻抗与力控' },
        { type: 'doc', id: 'foundations/controllers/integration', label: '7. 系统集成' },
        { type: 'doc', id: 'foundations/controllers/practice-roadmap', label: '8. 练习路线' },
      ],
    },
  ],

  foundationsVlmSidebar: [
    {
      type: 'category',
      label: '视觉语言大模型(VLM)',
      link: { type: 'doc', id: 'foundations/vlm/intro' },
      collapsible: false,
      items: [{ type: 'autogenerated', dirName: 'foundations/vlm' }],
    },
  ],

  foundationsVlaSidebar: [
    {
      type: 'category',
      label: '视觉-语言-动作大模型(VLA)',
      link: { type: 'doc', id: 'foundations/vla/vla-intro' },
      collapsible: false,
      items: [{ type: 'autogenerated', dirName: 'foundations/vla' }],
    },
  ],

  foundationsWorldModelSidebar: [
    {
      type: 'category',
      label: '世界模型(World Model)',
      link: { type: 'doc', id: 'foundations/world-model/placeholder' },
      collapsible: false,
      items: [{ type: 'autogenerated', dirName: 'foundations/world-model' }],
    },
  ],

  practicesOverviewSidebar: [
    'practices/intro',
    {
      type: 'category',
      label: '本体方向',
      collapsed: false,
      items: [
        { type: 'link', label: '机械臂方向', href: '/docs/practices/robot-arm/placeholder' },
        { type: 'link', label: '四足机器人', href: '/docs/practices/quadruped/placeholder' },
        { type: 'link', label: '双足 / 人形机器人', href: '/docs/practices/humanoid/placeholder' },
        { type: 'link', label: '移动操作', href: '/docs/practices/mobile-manipulation/placeholder' },
        { type: 'link', label: '轮足机器人', href: '/docs/practices/wheel-legged/placeholder' },
      ],
    },
    {
      type: 'category',
      label: '项目课程',
      collapsed: false,
      items: [
        { type: 'link', label: '从零到一搭建四足机器人', href: '/docs/practices/quadruped/cs123/intro' },
        { type: 'link', label: 'LeRobot 开源课程', href: '/docs/practices/robot-arm/data-collection/lerobot-course' },
        { type: 'link', label: 'SO-101 + LeRobot 真机教程', href: '/docs/practices/robot-arm/data-collection/so101-lerobot-real' },
        { type: 'link', label: '两轮足 Flamingo · Isaac Lab', href: '/docs/practices/wheel-legged/flamingo-isaaclab/preview' },
      ],
    },
  ],

  practicesRobotArmSidebar: [
    {
      type: 'category',
      label: '机械臂方向',
      link: { type: 'doc', id: 'practices/robot-arm/placeholder' },
      collapsible: false,
      items: [{ type: 'autogenerated', dirName: 'practices/robot-arm' }],
    },
  ],

  practicesQuadrupedSidebar: [
    {
      type: 'category',
      label: '四足机器人方向',
      link: { type: 'doc', id: 'practices/quadruped/placeholder' },
      collapsible: false,
      items: [
        { type: 'link', label: 'CS123 四足仿真课程', href: '/docs/practices/quadruped/cs123/intro' },
        { type: 'autogenerated', dirName: 'practices/quadruped/sim2sim' },
        { type: 'autogenerated', dirName: 'practices/quadruped/sim2real-guide' },
      ],
    },
  ],

  practicesCs123CourseSidebar: [
    {
      type: 'category',
      label: '从零到一搭建四足机器人',
      link: { type: 'doc', id: 'practices/quadruped/cs123/intro' },
      collapsible: false,
      items: [
        { type: 'doc', id: 'practices/quadruped/cs123/pid-control', label: '1. 执行器与 PD 控制' },
        { type: 'doc', id: 'practices/quadruped/cs123/forward-kinematics', label: '2. 正运动学' },
        { type: 'doc', id: 'practices/quadruped/cs123/inverse-kinematics', label: '3. 逆运动学' },
        { type: 'doc', id: 'practices/quadruped/cs123/quadruped-mjcf', label: '4. 搭建四足机器人' },
        { type: 'doc', id: 'practices/quadruped/cs123/gait-control', label: '5. 步态控制' },
        { type: 'doc', id: 'practices/quadruped/cs123/rl-gait', label: '6. 策略训练' },
        { type: 'doc', id: 'practices/quadruped/cs123/llm-control', label: '7. 语言控制' },
        { type: 'doc', id: 'practices/quadruped/cs123/perception', label: '8. 视觉感知' },
      ],
    },
  ],

  practicesLerobotCourseSidebar: [
    {
      type: 'category',
      label: 'LeRobot 开源课程',
      collapsible: false,
      items: ['practices/robot-arm/data-collection/lerobot-course/index'],
    },
  ],

  practicesSo101CourseSidebar: [
    {
      type: 'category',
      label: 'SO-101 + LeRobot 真机教程',
      collapsible: false,
      items: ['practices/robot-arm/data-collection/so101-lerobot-real/index'],
    },
  ],

  practicesHumanoidSidebar: [
    {
      type: 'category',
      label: '双足 / 人形机器人',
      link: { type: 'doc', id: 'practices/humanoid/placeholder' },
      collapsible: false,
      items: [{ type: 'autogenerated', dirName: 'practices/humanoid' }],
    },
  ],

  practicesMobileManipulationSidebar: [
    {
      type: 'category',
      label: '移动操作',
      link: { type: 'doc', id: 'practices/mobile-manipulation/placeholder' },
      collapsible: false,
      items: [{ type: 'autogenerated', dirName: 'practices/mobile-manipulation' }],
    },
  ],

  practicesWheelLeggedSidebar: [
    {
      type: 'category',
      label: '轮足机器人方向',
      link: { type: 'doc', id: 'practices/wheel-legged/placeholder' },
      collapsible: false,
      items: [
        { type: 'link', label: '两轮足 Flamingo · Isaac Lab', href: '/docs/practices/wheel-legged/flamingo-isaaclab/preview' },
      ],
    },
  ],

  practicesFlamingoCourseSidebar: [
    {
      type: 'category',
      label: '两轮足 Flamingo · Isaac Lab',
      collapsible: false,
      items: ['practices/wheel-legged/flamingo-isaaclab/preview'],
    },
  ],

  careerOverviewSidebar: [
    'career/intro',
    {
      type: 'category',
      label: '核心准备',
      collapsed: false,
      items: [
        { type: 'link', label: '岗位技能拆解', href: '/docs/career/job-skill-map/placeholder' },
        { type: 'link', label: '面经与八股', href: '/docs/career/interview-questions/placeholder' },
        { type: 'link', label: '招聘信息', href: '/docs/career/job-listings/placeholder' },
      ],
    },
  ],

  careerJobSkillMapSidebar: [
    {
      type: 'category',
      label: '岗位技能拆解',
      link: { type: 'doc', id: 'career/job-skill-map/placeholder' },
      collapsible: false,
      items: [{ type: 'autogenerated', dirName: 'career/job-skill-map' }],
    },
  ],

  careerInterviewQuestionsSidebar: [
    {
      type: 'category',
      label: '面经与八股',
      link: { type: 'doc', id: 'career/interview-questions/placeholder' },
      collapsible: false,
      items: [{ type: 'autogenerated', dirName: 'career/interview-questions' }],
    },
  ],

  careerResumePortfolioSidebar: [
    {
      type: 'category',
      label: '简历与作品集',
      link: { type: 'doc', id: 'career/resume-portfolio/placeholder' },
      collapsible: false,
      items: [{ type: 'autogenerated', dirName: 'career/resume-portfolio' }],
    },
  ],

  careerCompanyTechStacksSidebar: [
    {
      type: 'category',
      label: '公司技术栈',
      link: { type: 'doc', id: 'career/company-tech-stacks/placeholder' },
      collapsible: false,
      items: [{ type: 'autogenerated', dirName: 'career/company-tech-stacks' }],
    },
  ],

  careerJobListingsSidebar: [
    {
      type: 'category',
      label: '招聘信息',
      link: { type: 'doc', id: 'career/job-listings/placeholder' },
      collapsible: false,
      items: [{ type: 'autogenerated', dirName: 'career/job-listings' }],
    },
  ],

  careerCommunitySidebar: [
    {
      type: 'category',
      label: '社区与内推',
      link: { type: 'doc', id: 'career/community/placeholder' },
      collapsible: false,
      items: [{ type: 'autogenerated', dirName: 'career/community' }],
    },
  ],
};

export default sidebars;
