import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  overviewSidebar: [
    'overview/intro',
    'overview/embodied-ai-roadmap',
    'overview/learning-path',
    'overview/company-landscape',
    'overview/robotics-and-ros2-roadmap',
    'overview/algorithm-engineer-transition',
  ],

  foundationsSidebar: [
    'foundations/intro',
    {
      type: 'category',
      label: '具身智能入门',
      items: [{ type: 'autogenerated', dirName: 'foundations/embodied-ai-intro' }],
    },
    {
      type: 'category',
      label: '机器人运动学与 ROS2 基础',
      items: [{ type: 'autogenerated', dirName: 'foundations/robotics-and-ros2' }],
    },
    {
      type: 'category',
      label: '仿真工具基础',
      items: [{ type: 'autogenerated', dirName: 'foundations/simulation' }],
    },
    {
      type: 'category',
      label: '强化学习与控制',
      items: [{ type: 'autogenerated', dirName: 'foundations/rl-for-robotics' }],
    },
    {
      type: 'category',
      label: '视觉语言大模型(VLM)',
      items: [{ type: 'autogenerated', dirName: 'foundations/vlm' }],
    },
    {
      type: 'category',
      label: '视觉-语言-动作大模型(VLA)',
      items: [{ type: 'autogenerated', dirName: 'foundations/vla' }],
    },
    {
      type: 'category',
      label: '世界模型(World Model)',
      items: [{ type: 'autogenerated', dirName: 'foundations/world-model' }],
    },
  ],

  practicesOverviewSidebar: [
    'practices/intro',
    {
      type: 'category',
      label: '方向入口',
      collapsed: false,
      items: [
        { type: 'link', label: '机械臂方向', href: '/docs/practices/robot-arm/placeholder' },
        { type: 'link', label: '四足机器人', href: '/docs/practices/quadruped/placeholder' },
        { type: 'link', label: '双足 / 人形机器人', href: '/docs/practices/humanoid/placeholder' },
        { type: 'link', label: '移动操作', href: '/docs/practices/mobile-manipulation/placeholder' },
      ],
    },
    {
      type: 'category',
      label: '独立课程',
      collapsed: false,
      items: [
        { type: 'link', label: '从零到一搭建机器人', href: '/docs/practices/quadruped/cs123/intro' },
        { type: 'link', label: 'LeRobot 开源课程', href: '/docs/practices/robot-arm/data-collection/lerobot-course' },
        { type: 'link', label: 'SO-101 + LeRobot 真机教程', href: '/docs/practices/robot-arm/data-collection/so101-lerobot-real' },
      ],
    },
  ],

  practicesRobotArmSidebar: [
    {
      type: 'category',
      label: '机械臂方向',
      link: { type: 'doc', id: 'practices/robot-arm/placeholder' },
      collapsible: false,
      items: [{ type: 'autogenerated', dirName: 'practices/robot-arm' }],
    },
  ],

  practicesQuadrupedSidebar: [
    {
      type: 'category',
      label: '四足机器人方向',
      link: { type: 'doc', id: 'practices/quadruped/placeholder' },
      collapsible: false,
      items: [
        { type: 'link', label: 'CS123 四足仿真课程', href: '/docs/practices/quadruped/cs123/intro' },
        { type: 'autogenerated', dirName: 'practices/quadruped/sim2sim' },
        { type: 'autogenerated', dirName: 'practices/quadruped/sim2real-guide' },
      ],
    },
  ],

  practicesCs123CourseSidebar: [
    {
      type: 'category',
      label: '从零到一搭建机器人',
      link: { type: 'doc', id: 'practices/quadruped/cs123/intro' },
      collapsible: false,
      items: [
        { type: 'doc', id: 'practices/quadruped/cs123/pid-control', label: '1. 执行器与 PID 控制' },
        { type: 'doc', id: 'practices/quadruped/cs123/forward-kinematics', label: '2. 正运动学' },
        { type: 'doc', id: 'practices/quadruped/cs123/inverse-kinematics', label: '3. 逆运动学' },
        { type: 'doc', id: 'practices/quadruped/cs123/quadruped-mjcf', label: '4. 搭建四足机器人' },
        { type: 'doc', id: 'practices/quadruped/cs123/gait-control', label: '5. 步态控制' },
        { type: 'doc', id: 'practices/quadruped/cs123/rl-gait', label: '6. 强化学习步态训练' },
        { type: 'doc', id: 'practices/quadruped/cs123/llm-control', label: '7. LLM 控制' },
        { type: 'doc', id: 'practices/quadruped/cs123/perception', label: '8. 机器人视觉' },
      ],
    },
  ],

  practicesLerobotCourseSidebar: [
    {
      type: 'category',
      label: 'LeRobot 开源课程',
      collapsible: false,
      items: ['practices/robot-arm/data-collection/lerobot-course/index'],
    },
  ],

  practicesSo101CourseSidebar: [
    {
      type: 'category',
      label: 'SO-101 + LeRobot 真机教程',
      collapsible: false,
      items: ['practices/robot-arm/data-collection/so101-lerobot-real/index'],
    },
  ],

  practicesHumanoidSidebar: [
    {
      type: 'category',
      label: '双足 / 人形机器人',
      link: { type: 'doc', id: 'practices/humanoid/placeholder' },
      collapsible: false,
      items: [{ type: 'autogenerated', dirName: 'practices/humanoid' }],
    },
  ],

  practicesMobileManipulationSidebar: [
    {
      type: 'category',
      label: '移动操作',
      link: { type: 'doc', id: 'practices/mobile-manipulation/placeholder' },
      collapsible: false,
      items: [{ type: 'autogenerated', dirName: 'practices/mobile-manipulation' }],
    },
  ],

  careerSidebar: [
    'career/intro',
    {
      type: 'category',
      label: '岗位技能拆解',
      items: [{ type: 'autogenerated', dirName: 'career/job-skill-map' }],
    },
    {
      type: 'category',
      label: '面经与八股',
      items: [{ type: 'autogenerated', dirName: 'career/interview-questions' }],
    },
    {
      type: 'category',
      label: '简历与作品集',
      items: [{ type: 'autogenerated', dirName: 'career/resume-portfolio' }],
    },
    {
      type: 'category',
      label: '公司技术栈',
      items: [{ type: 'autogenerated', dirName: 'career/company-tech-stacks' }],
    },
    {
      type: 'category',
      label: '招聘信息',
      items: [{ type: 'autogenerated', dirName: 'career/job-listings' }],
    },
    {
      type: 'category',
      label: '转岗路径',
      items: [{ type: 'autogenerated', dirName: 'career/transition-paths' }],
    },
    {
      type: 'category',
      label: '社区与内推',
      items: [{ type: 'autogenerated', dirName: 'career/community' }],
    },
  ],
};

export default sidebars;
